[package]
edition = "2021"
name = "test-api"
publish = false
version = "0.2.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rocket = {version = "0.5.0-rc.2", features = ["json"]}
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.89"
uuid = {version = "1.1.2", features = ["v4"]}
