[package]
edition = "2021"
name = "test-api"
publish = false
version = "0.2.15"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rocket = {version = "0.5.1", features = ["json"]}
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.118"
uuid = {version = "1.9.0", features = ["v4"]}
