[package]
name = "libfatigue"
version = "0.2.11"
authors = ["Dylan Ross <pdylanross@gmail.com>"]
description = "an extensible load testing library"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/pdylanross/fatigue"
repository = "https://github.com/pdylanross/fatigue"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.73"
csv = "1.2.2"
dashmap = "5.2.0"
futures = "0.3.28"
hdrhistogram = "7.5.2"
humantime-serde = "1.1.1"
liquid = "0.26.4"
num_cpus = "1.16.0"
petname = "1.1.2"
reqwest = { version = "0.11.20", features = ["json"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
serde_yaml = "0.9.25"
thiserror = "1.0.47"
tokio = { version = "1.20.5", features = ["full"] }
url = "2.4.0"
