[package]
name = "libfatigue"
version = "0.2.7"
authors = ["Dylan Ross <pdylanross@gmail.com>"]
description = "an extensible load testing library"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/pdylanross/fatigue"
repository = "https://github.com/pdylanross/fatigue"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.57"
csv = "1.1.6"
dashmap = "5.2.0"
futures = "0.3.25"
hdrhistogram = "7.5.2"
humantime-serde = "1.1.1"
liquid = "0.26.0"
num_cpus = "1.13.1"
petname = "1.1.2"
reqwest = { version = "0.11.12", features = ["json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.85"
serde_yaml = "0.8.26"
thiserror = "1.0.37"
tokio = { version = "1.16.1", features = ["full"] }
url = "2.3.1"
