[package]
name = "libfatigue"
version = "0.2.11"
authors = ["Dylan Ross <pdylanross@gmail.com>"]
description = "an extensible load testing library"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/pdylanross/fatigue"
repository = "https://github.com/pdylanross/fatigue"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.67"
csv = "1.2.1"
dashmap = "5.2.0"
futures = "0.3.26"
hdrhistogram = "7.5.2"
humantime-serde = "1.1.1"
liquid = "0.26.1"
num_cpus = "1.13.1"
petname = "1.1.2"
reqwest = { version = "0.11.15", features = ["json"] }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
serde_yaml = "0.9.19"
thiserror = "1.0.40"
tokio = { version = "1.16.1", features = ["full"] }
url = "2.3.1"
