[package]
name = "libfatigue"
version = "0.2.3"
authors = ["Dylan Ross <pdylanross@gmail.com>"]
description = "an extensible load testing library"
edition = "2018"
readme = "README.md"
homepage = "https://github.com/pdylanross/fatigue"
repository = "https://github.com/pdylanross/fatigue"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.52"
dashmap = "5.0.0"
futures = "0.3.19"
hdrhistogram = "7.4.0"
humantime-serde = "1.0.1"
liquid = "0.23.1"
num_cpus = "1.13.1"
petname = "1.1.2"
reqwest = { version = "0.11.8", features = ["json"] }
serde = { version = "1.0.132", features = ["derive"] }
serde_yaml = "0.8.23"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"] }
url = "2.2.2"
