version: 2
updates:
  - package-ecosystem: cargo
    directory: "/" # Location of package manifests
    labels:
      - "dependencies"
      - "automerge"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
