version: 2
updates:
  - package-ecosystem: cargo
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      include: "scope"
      prefix: "chore"