[package]
name = "fatigue"
version = "0.2.7"
authors = ["Dylan Ross <pdylanross@gmail.com>"]
edition = "2018"
description = "an extensible load testing tool"
readme = "README.md"
homepage = "https://github.com/pdylanross/fatigue"
repository = "https://github.com/pdylanross/fatigue"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "2.34.0", features = ["suggestions", "color", "wrap_help"] }
console = "0.15.0"
crossterm = "0.23.2"
figment = { version = "0.10.6", features = ["env", "yaml"] }
humantime = "2.1.0"
itertools = "0.10.3"
libfatigue = { path = "../libfatigue", version = "0.2.7"}
num-format = "0.4.0"
prettytable-rs = "0.8.0"
serde = "1.0.140"
serde_json = "1.0.81"
thiserror = "1.0.31"
tokio = { version = "1.16.1", features = ["full"] }
