[package]
name = "fatigue"
version = "0.2.15"
authors = ["Dylan Ross <pdylanross@gmail.com>"]
edition = "2021"
description = "an extensible load testing tool"
readme = "README.md"
homepage = "https://github.com/pdylanross/fatigue"
repository = "https://github.com/pdylanross/fatigue"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.9", features = ["derive"] }
console = "0.15.8"
crossterm = "0.27.0"
figment = { version = "0.10.18", features = ["env", "yaml"] }
humantime = "2.1.0"
itertools = "0.12.1"
libfatigue = { path = "../libfatigue", version = "0.2.15" }
num-format = "0.4.4"
prettytable-rs = "0.10.0"
serde = "1.0.199"
serde_json = "1.0.116"
thiserror = "1.0.59"
tokio = { version = "1.37.0", features = ["full"] }
