name: Version Bump

on:
  workflow_run:
    workflows:
      - Continuous Integration
    branches:
      - main
    types:
      - completed

jobs:
  bump:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Bump
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-edit
          version: 0.8.0
          use-tool-cache: true
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
          branch: main
          commit: false
      - run: cargo set-version ${{ env.REVISION }} --workspace
      - run: cargo upgrade libfatigue@${{ env.REVISION }} --workspace
      - run: sudo chmod -R ugo+rwX .
      - uses: EndBug/add-and-commit@v7
        id: add-and-commit
        with:
          message: "Release ${{ env.REVISION }} [skip ci]"
          push: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: katyo/publish-crates@v1
        if: ${{ steps.add-and-commit.outputs.committed }}
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}