name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]
        toolchain: [stable]
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-targets
  cargo_sort:
    runs-on: ubuntu-latest
    name: Cargo Sort check
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-sort
          version: latest
      - run: cargo sort -c
  clippy_lint:
    runs-on: ubuntu-latest
    name: Cargo Clippy Check
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-deps