on:
  pull_request:
    branches:
      - main

name: Lint

jobs:
  check_commits:
    runs-on: ubuntu-latest
    name: Lint commit messages
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install CZ
        run: sudo pip3 install -U Commitizen
      - name: Cz Check
        run: cz check --rev-range ${{github.event.pull_request.base.sha}}..${{ github.event.pull_request.head.sha }}
  cargo_sort:
    runs-on: ubuntu-latest
    name: Cargo sort check
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-sort
          version: latest
      - run: cargo sort -c