name: Pull Request Validation

on:
  pull_request:
    branches:
      - main

jobs:
  check_commits:
    runs-on: ubuntu-latest
    name: Lint commit messages
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install CZ
        run: sudo pip3 install -U Commitizen
      - name: Cz Check
        run: cz check --rev-range ${{github.event.pull_request.base.sha}}..${{ github.event.pull_request.head.sha }}
