name: Publish

on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed

jobs:
  bump:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: publish release and crate
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ubuntu-latest
          shared-key: "pdylanross/fatigue"
      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-edit
          version: 0.11.9
          use-tool-cache: true
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@0.18.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
          commit: false
          push: false
      - run: cargo set-version ${{ env.REVISION }} --workspace
      - run: cargo upgrade libfatigue@${{ env.REVISION }} --workspace
      - uses: EndBug/add-and-commit@v9
        id: add-and-commit
        with:
          message: "[skip ci] release: ${{ env.REVISION }}"
          push: true
          tag: ${{ env.REVISION }}
      - run: sudo chmod -R ugo+rwX .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: katyo/publish-crates@v1
        name: Release lib
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          publish-delay: 1000
